Ghapiv4 2 run concurrently
ghuser-io/db pull request #22
Opened 2018-10-11 21:13 UTC by wowawiwa

What this PR does:
* In order to increase the rate limit, enables `fetchRepos` to run using both v3 and v4 of GitHub API concurrently.
* Fixes/Improves v4 driver
  * Fixes typo _pusher_at_
  * Fixes response structure for _owner_ field
  * Handle error when no primary language happens
  * Returns expected error codes when the GraphQL endpoint returns an error

Differences v4 driver compared to v3:
* There is no `webflow` user
* In the `repo` query, the `organization` field is just an empty object instead of containing information. When the owner is not an organization, there is no `organization` field at all.

2018-10-11 21:15 UTC, brillout commented
Awesome 😍

2018-10-20 17:02 UTC, lourot requested changes

2018-10-20 17:02 UTC, lourot commented on fetchRepos.js
> -          spinner.text = `${spinnerText} [${users.length}]`;
This was actually still quite useful to me, when I SSH to the machine running the fetchBot. This kind of loops can take several minutes and it's nice to see that the script isn't hanging.

But as you know, I intend to refactor all these big loops everywhere. So I suggest you don't worry about it and I'll push some refactoring in this branch on top of your work, and everything will get merged together at the end. Is it OK for you?

2018-10-20 17:02 UTC, lourot commented on fetchRepos.js
> +    full_names = [...referencedRepos];
Note for myself: I need to validate this kind of lines on the full DB, because we have more than 100k repos and this might be expensive.

2018-10-20 17:02 UTC, lourot commented on fetchRepos.js
> +      loopDo(full_names, async (full_name) => { await fetchRepo(ghclV4, full_name, firsttime)}),
I'll disable the v4-worker for now and as long as the front end isn't ready to deal with an empty repo.organization object. But it still has high-prio for me.

2018-10-20 17:02 UTC, lourot commented on impl/githubV4.js
>      // TODO: Use repoFetchedAtDate
Yep that's necessary (and actually the argument name isn't the best). If we don't do conditional requests, we'll consume the API credits 10x faster (maybe even 100x, I wouldn't be surprised).

The argument should be called `ifModifiedSince` at this level.

2018-10-20 17:03 UTC, AurelienLourot commented
Nice @wowawiwa, thanks, we're getting close to using GraphQL in production :)

2026-05-07 11:51 UTC, closed without merging